### ISSUE TITLE
Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by nscodelover** [wwan5803/react-modal-resizable-draggable#13]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

This warning happens when we have Mouse Click or Keyboard Press events (onMouseMove, onMouseUp, pressKey) after closed the dialog.
I think we should remove these event listeners in `componentWillUnmount()` life cycle.

![screen shot 2019-01-23 at 3 51 08 am](https://user-images.githubusercontent.com/25214541/51577686-5d0b7a00-1ec3-11e9-8548-7aad34d41a68.png)

**Comment by wwan5803** [comment]
Thank you for pointing out this issue. I'v fixed it already.

**Comment by nscodelover** [comment]
Thank you for updating.
