### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by baseljd** [wwan5803/react-modal-resizable-draggable#16]
I added some changes to the source and I'm try to build using `npm run build` off-course after running `npm install`.

I am getting this error without changing anything

> ERROR in ./src/index.js 13:4
Module parse failed: Unexpected token (13:4)
You may need an appropriate loader to handle this file type.
| 		if (isOpen) {
| 			return (
> 				<Fragment>
| 					<CSSTransition in={!isMinimised} timeout={300} classNames="minimise" unmountOnExit>
| 						<div

<img width="567" alt="Screen Shot 2019-04-22 at 3 02 15 PM" src="https://user-images.githubusercontent.com/6596236/56499581-a47bc380-650f-11e9-99d8-da8b7a05362e.png">

What am I missing?

**Comment by wwan5803** [comment]
Hi Baseljd, it seems the issue comes from one of loaders defined in webpack. May I ask what changes did you add?

**Comment by baseljd** [comment]
Tried to clone it and rebuild and it works fine. Seems I had something changed by mistake in webpack.

1. `git clone https://github.com/wwan5803/react-modal-resizable-draggable/issues/16`
2. `npm install`
3. `npm run build`
