### ISSUE TITLE
Closing React modal causing disabkeKeystroke is not defined error during componentnun mount

### ISSUE THREAD

**Issue by devamal2002** [wwan5803/react-modal-resizable-draggable#17]
main.js:1  Uncaught (in promise) ReferenceError: disableKeyStroke is not defined

**Comment by wwan5803** [comment]
Thanks for letting me know it. Solved it already.

**Comment by devamal2002** [comment]
Thanks. Would check. Got couple of questions. Is there any way to disable closure of modal if user clicks outside the modal? Is it configurable?  I mean leaving only a close button option inside the modal so that the user can choose to close it.

**Comment by shubhamsingla** [comment]
Hi, I installed this library today but I can still see this issue. Is there any way to get the fixed version?

**Comment by shubhamsingla** [comment]
v0.1.2 still has this issue. Could you please add the fixed version to the npm registry?

**Comment by deepikagunda** [comment]
Current version has this issue still . Will you be releasing a fix for this..

**Comment by wwan5803** [comment]
I'v tried to reproduce this issue but failed. I started a new project and everything works fine. Could you please give me more details

**Comment by vikasvaviya68** [comment]
i have same issue, on close model it will give this error 

![image](https://user-images.githubusercontent.com/52752059/62110346-d4cfbc80-b2cb-11e9-883c-fcf90dcfe540.png)

**Comment by nileshbhingaradiya** [comment]
I fond the issue , i think on `componentWillUnmount` method `const { disableKeystroke } = this.props;` is missing 
![image](https://user-images.githubusercontent.com/28615068/62112555-8ec92780-b2d0-11e9-860d-59257c63c1c9.png)

**Comment by nileshbhingaradiya** [comment]
This is PR for a fix issue 
https://github.com/wwan5803/react-modal-resizable-draggable/pull/23/files

**Comment by dartess** [comment]
@wwan5803 version in npm is slill broken
