### ISSUE TITLE
Module not found: Can't resolve 'react-modal-resizable-draggable'

### ISSUE THREAD

**Issue by Tycholiz** [wwan5803/react-modal-resizable-draggable#18]
Having trouble installing this library. 

**Logs when I _yarn add_:**
`warning "react-modal-resizable-draggable > react-icons > react-icon-base@2.1.0" has unmet peer dependency "prop-types@*".
warning " > react-modal-resizable-draggable@0.1.1-rc.16" has incorrect peer dependency "react@^15.5.4".
`

**package.json**
`"dependencies": {
    "react": "^16.8.3",
    "react-dom": "^16.8.3",
    "react-markdown": "^4.0.8",
    "react-modal-resizable-draggable": "^0.1.1-rc.16",
    "react-scripts": "2.1.5"
  },`

Error message when trying to _yarn start_
./src/components/Modal.js
Module not found: Can't resolve 'react-modal-resizable-draggable' in '/home/kyle/programming/projects/interactive-modal-chart/src/components'

**Comment by wwan5803** [comment]
The warning message should not block the process of installation. But could you try npm install instead?

**Comment by rafinha90** [comment]
I'm having the same problem.

Tried installing with npm and yarn on two different computers.

I'm using that "create-react-app", if this can help...

**Comment by wwan5803** [comment]
@Tycholiz @rafinha90 I'v fix the problem. please run npm install react-modal-resizable-draggable and try again
