### ISSUE TITLE
[disableKeystroke] componentWillUnmount 

### ISSUE THREAD

**Issue by Lincerossa** [wwan5803/react-modal-resizable-draggable#22]
Downloading it from npm, it has this error.

/src/index.js
line 84 -> disableKeystroke is not defined

It needs to be defined as 
**const { disableKeystroke } = this.props**
at line 81

**Comment by mrkyel** [comment]
Your code is also not working.

**Comment by mrkyel** [comment]
All of you 
also should have to fix the code "componentWillUnmount" like a "ComponentDidMount"
in the main.js

For example, just add the code (var t=this.props.disableKeystroke;) 
and add 't' before '||'

Maybe you can find what it is.

**Comment by mrkyel** [comment]
However,
after fixing it, we still can see this message and I couldn't fix it.
'can't perform a react state update on an unmounted component'

**Comment by BhavikModi** [comment]
@mrkyel 
Is this already fixed?
If not -
Can you give me code to fix this?

**Comment by wwan5803** [comment]
Fixed, and you are welcome to fork this project for any purpose
