### ISSUE TITLE
If i want to disable the keyboard button support ? How to  do that.

### ISSUE THREAD

**Issue by praveenpatel2050** [wwan5803/react-modal-resizable-draggable#32]
I want to disable keyboard button support for modal move . How  i disable that.

**Comment by praveenpatel2050** [comment]
What if i use model and in modal i have text box. When I am use arrow key for move my cursor in input box, The Whole modal is move with pressing the arrow key(left,right,top,bottom).

I am use disableMove : true for the onFocus on text element.

**Comment by wwan5803** [comment]
set the disableMove to the ReactModal should work.
<img width="718" alt="Screen Shot 2020-07-19 at 12 14 12 pm" src="https://user-images.githubusercontent.com/6858452/87865504-a2760e00-c9b9-11ea-8d6a-6a70278d22df.png">

**Comment by canselcik** [comment]
@wwan5803 I believe you meant to say `disableKeystroke={true}`.

Just posting here for reference in case someone comes across this in the future.
