### ISSUE TITLE
Not able move vertically down once reaches top of the screen

### ISSUE THREAD

**Issue by sred36** [wwan5803/react-modal-resizable-draggable#5]
Moving the modal  top edge of screen and i am not able to move down vertically

Can you fix the issue
![image](https://user-images.githubusercontent.com/35680138/43247306-eb30e2fa-90d1-11e8-8b44-983110d0bd57.png)

**Comment by wwan5803** [comment]
To fix this issue, you can add the following css to your project. So the draggable area will be 4 sides of the modal.

. flexible-modal-drag-area-left{
    background: rgba(22, 22, 333, 0.2);
    width: 50px;
    position:absolute;
    left:0;
    top:0;
    cursor:move;
}

. flexible-modal-drag-area-right{
    background: rgba(22, 22, 333, 0.2);
    width: 50px;
    position:absolute;
    right:0;
    top:0;
    cursor:move;
}

. flexible-modal-drag-area-bottom{
    background: rgba(22, 22, 333, 0.2);
    height: 50px;
    position:absolute;
    left:0;
    bottom:0;
    cursor:move;
}

**Comment by soner8** [comment]
Is it possible to prevent modal to go out of window ?
